name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: evelynmosca
          outputs: |
            dist/snake.svg?color_snake=#a855f7&color_dots=#0d1117,#1f2937,#334155,#60a5fa,#93c5fd

      - name: Push
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
